-- vim.keymap.set('', '<C-n>', '<esc>:NvimTreeToggle<CR>')	-- 设置开关目录树
-- vim.keymap.set('!', '<C-n>', '<esc>:NvimTreeToggle<CR>')
-- bufferline 左右Tab切换
-- vim.keymap.set("", "<A-Left>", "<esc>:BufferLineCyclePrev<CR>")
-- vim.keymap.set("", "<A-Right>", "<esc>:BufferLineCycleNext<CR>")
-- vim.keymap.set("", "<A-w>", "<esc>:BufferLinePickClose<CR>")
